### PR TITLE
add first version of memcache storage plugin

### PR DESCRIPTION
**Pull request by zandbelt**
need to replace current machine-wide locks with distributed locking through memcache operations later

### CODE REVIEW

**Comment by bungle** [comment]
Wow, that was fast. Looks nice. This is a good reference using Redis as a backend and Redis locking:
https://github.com/snc/SncRedisBundle/blob/master/Session/Storage/Handler/RedisSessionHandler.php

This is example of memcache:
https://github.com/LeaseWeb/LswMemcacheBundle/blob/master/Session/Storage/LockingSessionHandler.php

The API is a bit different in PHP because it has a lot of legacy. I think that you can follow the same procedure with memcache as that LswMemcacheBundle uses for locking.

You could also support lockless version (locking version should be the default). I actually modified my shm storage to work without locks:
https://github.com/bungle/lua-resty-session/commit/e011e904fd233e82412c824b677e35a99d3cd802

If you don't want to have locks with shm, you just don't create shared dict for locks:

```nginx
# uncomment to enable locking
#lua_shared_dict sessions_locks 1m;
```

**Comment by bungle** [comment]
This is starting to look really promising. A few comments:

1. You can use `memcached.touch` here (instead of `set`): https://github.com/zandbelt/lua-resty-session/blob/storages/lib/resty/session/storage/memcache.lua#L60 (shm didn't have a way to modify just the expiration).
2. The better place to open connection is probably in the `open` function (https://github.com/zandbelt/lua-resty-session/blob/storages/lib/resty/session/storage/memcache.lua#L48)
3. `self.memc:close()` should also be called on save when the close argument is true.
4. Instead of `local lockprefix`  it is better to have:

```lua
local prefix   = ngx.var.session_memcache_prefix or "sessions"
```

And (for a session key and lock key you can use something like this):

```lua
local concat = table.concat
-- Example of generating session key that is used as a memcached session key
local sk = concat({ prefix, prefix encode(i) }, ":" )
-- Example of generating lock key that is used as a memcached locking key
local lk = concat({ sk, "lock }, "." )
```

So by default we have keys like these in memcached:

```
sessions:1
sessions:1.lock
sessions:2
sessions:3
etc.
```

5. Parsing booleans (https://github.com/zandbelt/lua-resty-session/blob/storages/lib/resty/session/storage/memcache.lua#L12), for that I added session.utils.enabled function, so change that line to:

```lua
local enable = utils.enabled
local uselocking = enabled(ngx.var.session_memcache_uselocking or true)
```

6. Parsing numbers (https://github.com/zandbelt/lua-resty-session/blob/storages/lib/resty/session/storage/memcache.lua#L14-L16), you should use:

```lua
local port         = tonumber(ngx.var.session_memcache_port) or 11211
local spinlockwait = tonumber(ngx.var.session_memcache_spinlockwait) or 10000
local maxlockwait  = tonumber(ngx.var.session_memcache_maxlockwait) or 30
```

After you get this done, it is just copy and paste to from your code to add Redis support. So we are really close to merging this. At first I will merge this to storage branch and then we/I just have to do rest of the things like documenting this. I think that I will end up releasing this during the next two weeks.

**Comment by zandbelt** [comment]
done, except I could not get memc:connect to work reliably in the open function

**Comment by bungle** [comment]
Great! Can you elaborate a little bit what kind of issues did you have with connect in open function? I may have missed something important. I can see one problem here. If user opens readonly session aka just calls:

```lua
local s = require "resty.session".open()
local uid = s.uid
```

And does nothing else. Then there is a possibility that we don't call `memcached:close`. There is no other hooks than `__gc` metamethod that we could hook. We could add another function (`close`) to session that user can call on read-only session.

Other way around this is that we don't keep connection open, but always grap a new one when we want to access memcached, say a local `function connect()`, and immediately close it when accessing it is done (and instead of closing, we could just use `set_keepalive` (https://github.com/openresty/lua-resty-memcached#set_keepalive). For set keepalive we could add a few config variables:

```lua
local pool_timeout = tonumber(ngx.var.session_memcache_pool_timeout)
local pool_size  = tonumber(ngx.var.session_memcache_pool_size)
```

What do you think. I'm leaning a little bit towards connecting and set_keepalive whenever access is needed (no storage function will leave then connection open). I'm not sure though if this has some performance penalty, but I suppose that getting connection from a pool is rather quick. This way we don't need to add a new close function that user needs to remember to call. Connect-late, release early approach.

What do you think?

One minor thing though, we should also support Unix sockets, e.g.:

```lua
local socket = ngx.var.session_memcache_socket
```

If `socket` is defined it will be preferred. Otherwise we use `server` and `port` (could you also rename server to `host` – that's a little bit more common).

Looks pretty damn nice to me! I'm really happy about this.

**Comment by zandbelt** [comment]
here you go; the current approach does not seem to have the problem that I had earlier (which was:  `attempt to send data on a closed socket`)

**Comment by bungle** [comment]
Ok, this looks good. I will merge now. I also built redis adapter, and thanks to you it was rather easy to implement. The redis adapter can be found here:
https://github.com/bungle/lua-resty-session/blob/storages/lib/resty/session/storage/redis.lua

**Comment by bungle** [comment]
I have made some changes to code. It would be nice if you could test the latest from my storages branch. Also, please comment if you find anything strange or something that you don't agree.

**Comment by zandbelt** [comment]
The changes work for me. I have 2 remarks about the code: in the current code there are a number of functions that have multiple return paths preceded with some cleanup statements; I'd rather see a single return path when it needs to be combined with cleanup anyway. Perhaps it is just a matter of style though, I can live with it either way ;-)

The other remark is probably slightly more important: there are so many similarities between redis and memcache that it makes sense to create refactor it. In OO one would create an abstract class to handle generic code and call abstract lock/unlock/connect/disconnect/get/set methods. I'm a Lua newbie so I'm not sure where to start that.

**Comment by bungle** [comment]
Good to know it works. Yes, multiple return statements are sometimes considered a bad practice, but using them can help reduce nesting and make the code shorter and use less variables (and avoid using gotos). Yes, these are also matters of style and preferences.

For other remark. Yes there a lot of overlapping similar code. But then again, it is easy to understand. All the redis code is in redis.lua and all the memcache code is in memcache.lua. So it is rather easy to read and you don't need to jump between files too much. These are actually just something like less than 100 lines of code. I can live with that copy-paste duplication. It also makes it easier to test. When using abstract class or subclassing, and making changes to parent, we need to check that we didn't break anything in those that inherit them. I think that current approach lets work better on these concurrently (someone working on enhancing memcache adapter doensn't need to coordinate the efforts with someone enhancing redis adapter – we can see a lot of similarities, but that doesn't mean that it is permanent state, I mean with this separate copy-paste code, we can freely go to any direction with redis and memcache and they doesn't need to follow the same path). This is a new thing in lua-resty-session, so I rather see where it goes before nailing things with some abstract base prototype table (as in Lua).

So let's leave this as it is know and see if any issues will arise and fix those. With server side adapters we have many more places for failures, so we might need to implement some logging in adapters and/or session.lua.

One thing I'm also thinking about is the adapter configuration. Right now the only place to configure them is from nginx.conf(igs). Should we allow configuration to be in code as well (as we allow with session.lua), aka parameters to adapter.new(). Should we allow session configs and session adapter config in these server side mediums too (memcached, redis etc.) – maybe that is too much and can be left to users if we support adapter.new arguments (but there is already set_by_lua as well)? What would that flexibility to mean to code, and its complexity and performance.

Also, should we add __gc metamethod to redis/memcache adapters to close connections and unlock locks on garbage collection. If the user forgots that. And whatabout, should we block writing to session.data if it is opened as readonly or destroyed. And if destroyed, should we also block reading. This would mean that we need to have metatable on session.data table (and maybe even set and get functions instead of directly accessing session.data). Should we also block session.save and session.destroy if the session was opened with session:open (read-only) and not session:start. The approach we have now is that we trust that users do the right thing and be adults and fix the bugs if they don't. The question is that should we still have safe-guards and baby-sitting things in place? Or maybe we just wait for the first angry guy who reports a hard to debug problem he is having with session, and then find a solution. These choices always have side-effects. And adding more code, means usually more edge-cases and places for bugs, and sometimes breaks bc. So I think that best way to proceed is evolutionary approach, where we first get an observation, and then act upon it, and not try to fix all the possible, but rare (non-issues), proactively.

Then we might also look if we want to have more serializers and pluggable encryption.

As always, the contributions and opinions etc. are greatly welcomed.

**Comment by zandbelt** [comment]
agreed on the evolutionary approach: it would be good to get this out first and get feedback from others before making more changes

**Comment by bungle** [comment]
Thank for reminding this.

**Pull request merged**
