### PR TITLE
make redis storage can connect to a authenticated redis

### PR DESCRIPTION
**Pull request by cheng5533062**
I changed some code in the storage/redis.lua to make the redis storage can connect to a authenticated redis. add a nginx variable "session_redis_auth“ to config the redis password. I test it use you demo only,no more test has been made.

### CODE REVIEW

**Comment by bungle** [comment]
@cheng5533062,

Super cool thanks, one question though. Is this neccessary;'

```lua
if ok then
    local c
    c,err = self.redis:get_reused_times()
    if 0 == c then
        ok,err = self.redis:auth(self.auth)
    end
end
```

Is this enough:

```lua
if ok and self.auth then
    ok,err = self.redis:auth(self.auth)
end
```

**Comment by bungle** [comment]
Also add space to `ok,err` => `ok, err`

**Comment by bungle** [comment]
Ah I got it why there is that `self.redis:get_reused_times()`. Well maybe like this then:

```lua
if ok and self.auth then
    ok, err = self.redis:get_reused_times()
    if ok == 0 then
        ok, err = self.redis:auth(self.auth)
    end
end
```

**Comment by bungle** [comment]
Well, forget about it, lets merge this and I make my own adjustments if I see need for it. Thanks.

**Comment by cheng5533062** [comment]
oh yes, I forgot to deal with the nil value of the auth. if the auth not been set, it gets wrong. so glad you fix that. 
there is a kind of time difference between us,so I haven't replay that just in time

**Pull request merged**
